# Generated by Django 3.1.3 on 2020-12-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=150)),
                ('lastname', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MN', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NWT', 'Northwest Terrorities'), ('NS', 'Nova Scotia'), ('NV', 'Nunavut'), ('ON', 'Ontario'), ('PEI', 'Prince Edward Island'), ('QB', 'Quebec'), ('SAS', 'Saskatchewan'), ('YUK', 'Yukon')], default='ON', max_length=150)),
                ('address', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(default='09:00', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('activity', models.CharField(default='Korean Food', max_length=50)),
                ('user_invite', models.ForeignKey(default='none', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.scheduleusers')),
            ],
        ),
    ]
