# Generated by Django 3.1.3 on 2020-12-05 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201205_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(default='12:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 19, 31, 44, 600655, tzinfo=utc), max_length=50),
        ),
    ]
