# Generated by Django 3.1.3 on 2020-12-15 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201205_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 2, 14, 40, 378809, tzinfo=utc), max_length=50),
        ),
    ]
