# Generated by Django 3.1.3 on 2021-01-06 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201214_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 1, 56, 45, 264966, tzinfo=utc), max_length=50),
        ),
    ]
