# Generated by Django 3.1.3 on 2021-01-06 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210105_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 2, 43, 5, 249000, tzinfo=utc), max_length=50),
        ),
    ]
