# Generated by Django 3.1.3 on 2021-01-07 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210105_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 7, 0, 37, 52, 97946, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_invite',
            field=models.ForeignKey(default='none', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.scheduleusers', to_field='firstname'),
        ),
        migrations.AlterField(
            model_name='scheduleusers',
            name='firstname',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
