# Generated by Django 3.2.6 on 2021-08-11 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210106_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 16, 50, 12, 603970, tzinfo=utc), max_length=50),
        ),
    ]
